site_name: VelNet Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: red
    # background: custom
  font:
    # text: Oswald
    # text: Merriweather
    text: Merriweather Sans
  logo: assets/logo.png

extra_css:
  - stylesheets/extra.css
# theme:
#   name: material
#   palette:
#     # Palette toggle for dark mode
#     - scheme: custom
#       media: "(prefers-color-scheme: dark)"
#       # primary: custom
#       toggle:
#         icon: material/weather-sunny
#         name: Switch to light mode

#     # Palette toggle for light mode
#     - scheme: default
#       media: "(prefers-color-scheme: light)"
#       toggle:
#         icon: material/weather-night
#         name: Switch to dark mode
